[project]
org-name= "wso2"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "utils"
    path = "/home/miyurud/git/ballerina-eth-utils/target/bin/utils.jar"
    groupId = "wso2"
    modules = ["utils"]