[project]
org-name= "wso2"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "utils"
    path = "/home/miyurud/git/ballerina-eth-utils/target/bin/utils.jar"
    groupId = "wso2"
    modules = ["utils"]

    [[platform.libraries]]
    artifactId = "abc"
    path = "/home/miyurud/.m2/repository/mysql/mysql-connector-java/5.1.46/mysql-connector-java-5.1.46.jar"
    groupId = "abc"
    modules = ["utils", "issuer", "chat"]